---
- name: libselinux-python install
  yum:
    name: libselinux-python
    state: present
  when: inventory_hostname == "inetRouter" or inventory_hostname == "centralRouter"

- name: Bond module for centos6
  shell: modprobe bonding
  when: inventory_hostname == "inetRouter"

- name: Add bond module
  modprobe:
    name: bonding
    state: present
  when: inventory_hostname == "centralRouter"

- name: Copy config for inetRouter bond0
  copy: src="ifcfg-bond0_iR" dest=/etc/sysconfig/network-scripts/ifcfg-bond0
  notify: restart network
  when: inventory_hostname == "inetRouter"

- name: Copy config for inetRouter eth1
  copy: src="ifcfg-eth1" dest=/etc/sysconfig/network-scripts/ifcfg-eth1
  notify: restart network
  when: inventory_hostname == "inetRouter"

- name: Copy config for inetRouter eth2
  copy: src="ifcfg-eth2" dest=/etc/sysconfig/network-scripts/ifcfg-eth2
  notify: restart network
  when: inventory_hostname == "inetRouter"

- name: Copy config for centralRouter bond0
  copy: src="ifcfg-bond0_cR" dest=/etc/sysconfig/network-scripts/ifcfg-bond0
  notify: restart network
  when: inventory_hostname == "centralRouter"

- name: Copy config for centralRouter eth1
  copy: src="ifcfg-eth1" dest=/etc/sysconfig/network-scripts/ifcfg-eth1
  notify: restart network
  when: inventory_hostname == "centralRouter"

- name: Copy config for centralRouter eth2
  copy: src="ifcfg-eth2" dest=/etc/sysconfig/network-scripts/ifcfg-eth2
  notify: restart network
  when: inventory_hostname == "centralRouter"

- name: Config for testClient1
  copy: src="ifcfg-eth1.10_tC1" dest=/etc/sysconfig/network-scripts/ifcfg-eth1.10
  notify: restart network
  when: inventory_hostname == "testClient1"

- name: Config for testClient2
  copy: src="ifcfg-eth1.20_tC2" dest=/etc/sysconfig/network-scripts/ifcfg-eth1.20
  notify: restart network
  when: inventory_hostname == "testClient2"

- name: Config for testServer1
  copy: src="ifcfg-eth1.10_tS1" dest=/etc/sysconfig/network-scripts/ifcfg-eth1.10
  notify: restart network
  when: inventory_hostname == "testServer1"

- name: Config for testServer2
  copy: src="ifcfg-eth1.20_tS2" dest=/etc/sysconfig/network-scripts/ifcfg-eth1.20
  notify: restart network
  when: inventory_hostname == "testServer2"
