---
- hosts: inetRouter:centralRouter
  name: bond for routers
  become: yes
  roles:
    - role: bond

- hosts: testClient1:testClient2:testServer1:testServer2
  name: vlan for tests
  become: yes
  roles:
    - role: vlan
