---
- name: Config for testClient1
  copy: src="ifcfg-eth1.10_tC1" dest=/etc/sysconfig/network-scripts/ifcfg-eth1.10
  notify: restart network
  when: inventory_hostname == "testClient1"

- name: Config for testClient2
  copy: src="ifcfg-eth1.20_tC2" dest=/etc/sysconfig/network-scripts/ifcfg-eth1.20
  notify: restart network
  when: inventory_hostname == "testClient2"

- name: Config for testServer1
  copy: src="ifcfg-eth1.10_tS1" dest=/etc/sysconfig/network-scripts/ifcfg-eth1.10
  notify: restart network
  when: inventory_hostname == "testServer1"

- name: Config for testServer2
  copy: src="ifcfg-eth1.20_tS2" dest=/etc/sysconfig/network-scripts/ifcfg-eth1.20
  notify: restart network
  when: inventory_hostname == "testServer2"
